const registrations = [
  { names: "Ana Clara e Lucas", classes: "2º ADM", committee: "ONU Mulheres", country: "Afeganistão", flag: "af", status: "confirmed" },
  { names: "Bianca e Rafael", classes: "1º D.S.", committee: "FAO", country: "Brasil", flag: "br", status: "reserved" },
  { names: "Gabriel e Pedro", classes: "3º ADM", committee: "CSNU", country: "Japão", flag: "jp", status: "confirmed" },
  { names: "Letícia e Marina", classes: "2º ADM", committee: "UNICEF", country: "Canadá", flag: "ca", status: "confirmed" },
  { names: "Thiago e Vinícius", classes: "1º D.S.", committee: "OMS", country: "Índia", flag: "in", status: "confirmed" }
];
const committeeData = [["ONU Mulheres", "Sala 12", 5, 38], ["FAO", "Sala 08", 3, 23], ["CSNU", "Auditório", 4, 31], ["UNICEF", "Sala 15", 2, 15], ["ACNUDH", "Sala 11", 1, 8], ["OMS", "Laboratório 02", 4, 31], ["PNUD", "Sala 06", 2, 15], ["UNESCO", "Sala 09", 0, 0]];
const state = { page: "overview", period: "Manhã" };
const adminStage = document.querySelector("#admin-stage");
const pageTitle = document.querySelector("#page-title");
const dialog = document.querySelector("#admin-dialog");

function row(item) { const label = item.status === "reserved" ? "Reservada" : "Confirmada"; return `<tr><td><div class="duo"><strong>${item.names}</strong><small>${item.classes}</small></div></td><td>${item.committee}</td><td><img class="flag" src="https://flagcdn.com/w40/${item.flag}.png" srcset="https://flagcdn.com/w80/${item.flag}.png 2x" alt="" />${item.country}</td><td><span class="state ${item.status}">${label}</span></td></tr>`; }
function table(items = registrations) { return `<div class="panel"><div class="panel-header"><h2>Inscrições recentes</h2><button class="text-button" data-page="registrations" type="button">Ver todas</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>Dupla</th><th>Comitê</th><th>País</th><th>Status</th></tr></thead><tbody>${items.map(row).join("")}</tbody></table></div></div>`; }
function overview() { return `<section class="stats"><article class="stat"><span class="stat-label">Inscrições confirmadas</span><strong>42</strong><span class="detail">de 207 vagas</span></article><article class="stat progress-stat"><span class="stat-label">Ocupação do período</span><strong>20%</strong><div class="mini-progress"><i style="width:20%"></i></div></article><article class="stat"><span class="stat-label">Reservas em andamento</span><strong>3</strong><span class="detail">expiram em até 5 min</span></article></section><section class="content-grid">${table()}<aside class="panel"><div class="panel-header"><h2>Comitês e locais</h2><button class="text-button" data-page="committees" type="button">Gerenciar</button></div>${committeeRows(false, 4)}</aside></section>`; }
function committeeRows(withActions = false, limit = committeeData.length) { return committeeData.slice(0, limit).map(([name, location, count, progress]) => `<div class="committee-row"><div><strong>${name}</strong><small>${location} · ${count} de 13 vagas</small><div class="mini-progress"><i style="width:${progress}%"></i></div></div><div class="committee-side">${withActions ? `<div class="row-actions"><button class="row-button" data-action="view-committee" data-committee="${name}" type="button">Ver</button><button class="row-button" data-action="edit-committee" data-committee="${name}" type="button">Editar</button><button class="row-button danger" data-action="delete-committee" data-committee="${name}" type="button">Excluir</button></div>` : ""}<span class="state available">Ativo</span></div></div>`).join(""); }
function registrationsPage() { const options = (values, label, id) => `<select id="${id}" class="filter-select" aria-label="Filtrar por ${label}"><option value="">${label}: todos</option>${[...new Set(values)].map(value => `<option value="${value}">${value}</option>`).join("")}</select>`; return `<section class="registration-page"><div class="filters"><input id="filter" class="filter-input" placeholder="Buscar por dupla" aria-label="Buscar inscrições" />${options(registrations.map(item => item.classes), "Turma", "filter-class")}${options(registrations.map(item => item.committee), "Comitê", "filter-committee")}${options(registrations.map(item => item.country), "País", "filter-country")}</div>${table()}</section>`; }
function slots() { const list = [["CSNU", "Brasil", "br", "occupied"], ["CSNU", "Japão", "jp", "occupied"], ["FAO", "Brasil", "br", "reserved"], ["ONU Mulheres", "Canadá", "ca", "available"], ["UNICEF", "França", "fr", "available"], ["OMS", "Índia", "in", "occupied"]]; return `<section class="slots-grid">${list.map(([committee,country,flag,status]) => `<article class="slot"><p>${committee}</p><h3><img class="flag" src="https://flagcdn.com/w40/${flag}.png" alt="" />${country}</h3><span class="state ${status}">${status === "available" ? "Disponível" : status === "reserved" ? "Reservada" : "Ocupada"}</span></article>`).join("")}</section>`; }
function committeesPage() { return `<section class="panel"><div class="panel-header"><div><h2>Comitês ativos</h2><span class="panel-subtitle">Local definido para cada simulação.</span></div><button class="new-button" data-action="add-committee" type="button">+ Adicionar comitê</button></div>${committeeRows(true)}</section>`; }
function render() { const pages = { overview: ["Visão geral", overview], registrations: ["Inscrições", registrationsPage], slots: ["Vagas", slots], committees: ["Comitês", committeesPage] }; const [title, view] = pages[state.page]; pageTitle.textContent = title; adminStage.innerHTML = view(); document.querySelectorAll(".nav-item").forEach(button => button.classList.toggle("active", button.dataset.page === state.page)); }
document.addEventListener("click", event => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.page) { state.page = button.dataset.page; render(); } if (button.dataset.period) { state.period = button.dataset.period; document.querySelectorAll("[data-period]").forEach(item => item.classList.toggle("active", item.dataset.period === state.period)); } if (button.dataset.action === "menu") document.querySelector(".sidebar").classList.toggle("open"); if (button.dataset.action === "new-registration") { document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">NOVA INSCRIÇÃO</p><h2>Cadastro manual</h2><p>Na integração com o Supabase, este botão abrirá o mesmo fluxo de inscrição para a organização cadastrar uma dupla manualmente.</p><button class="dialog-action" data-action="close-dialog">Entendi</button>`; dialog.showModal(); } if (button.dataset.action === "add-committee") { document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">COMITÊS</p><h2>Adicionar um comitê</h2><p>A criação e edição serão conectadas ao banco após a validação desta interface.</p><button class="dialog-action" data-action="close-dialog">Entendi</button>`; dialog.showModal(); } if (button.dataset.action === "close-dialog") dialog.close(); });
document.addEventListener("input", event => { if (event.target.id !== "filter") return; const term = event.target.value.toLowerCase(); const filtered = registrations.filter(item => `${item.names} ${item.committee} ${item.country}`.toLowerCase().includes(term)); const body = adminStage.querySelector("tbody"); if (body) body.innerHTML = filtered.map(row).join(""); });
function applyRegistrationFilters() { const term = document.querySelector("#filter")?.value.toLowerCase() || ""; const selectedClass = document.querySelector("#filter-class")?.value || ""; const committee = document.querySelector("#filter-committee")?.value || ""; const country = document.querySelector("#filter-country")?.value || ""; const filtered = registrations.filter(item => `${item.names} ${item.committee} ${item.country}`.toLowerCase().includes(term) && (!selectedClass || item.classes === selectedClass) && (!committee || item.committee === committee) && (!country || item.country === country)); const body = adminStage.querySelector("tbody"); if (body) body.innerHTML = filtered.map(row).join("") || `<tr><td colspan="4">Nenhuma inscrição encontrada.</td></tr>`; }
document.addEventListener("input", event => { if (["filter", "filter-class", "filter-committee", "filter-country"].includes(event.target.id)) applyRegistrationFilters(); });
document.addEventListener("change", event => { if (["filter-class", "filter-committee", "filter-country"].includes(event.target.id)) applyRegistrationFilters(); });
document.addEventListener("click", event => { const button = event.target.closest("button"); if (!button || button.dataset.action !== "export") return; const header = ["Dupla", "Turma", "Comitê", "País", "Status"]; const lines = registrations.map(item => [item.names, item.classes, item.committee, item.country, item.status === "reserved" ? "Reservada" : "Confirmada"]); const csv = [header, ...lines].map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `inscricoes_onutec_${state.period.toLowerCase()}.csv`; link.click(); URL.revokeObjectURL(link.href); });
document.addEventListener("click", event => { const button = event.target.closest("button"); if (!button || !button.dataset.committee) return; const item = committeeData.find(([name]) => name === button.dataset.committee); if (!item) return; const [name, location, count] = item; if (button.dataset.action === "view-committee") document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">${location.toUpperCase()}</p><h2>${name}</h2><p>${count} vagas ocupadas de 13 no período da ${state.period.toLowerCase()}.</p><button class="dialog-action" data-action="close-dialog">Fechar</button>`; if (button.dataset.action === "edit-committee") document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">EDITAR COMITÊ</p><h2>${name}</h2><label class="dialog-field">Local / sala<input value="${location}" /></label><button class="dialog-action" data-action="close-dialog">Salvar alterações</button>`; if (button.dataset.action === "delete-committee") document.querySelector("#dialog-content").innerHTML = `<p class="eyebrow">EXCLUIR COMITÊ</p><h2>Excluir ${name}?</h2><p>Na versão conectada, inscrições confirmadas serão preservadas e a ação exigirá confirmação.</p><button class="dialog-action danger-action" data-action="close-dialog">Excluir comitê</button>`; if (["view-committee", "edit-committee", "delete-committee"].includes(button.dataset.action)) dialog.showModal(); });
render();
