const committees = {
  "ONU Mulheres": ["Afeganistão", "África do Sul", "Alemanha", "Arábia Saudita", "Canadá", "China", "EUA", "Índia", "Japão", "Noruega", "Países Baixos", "Reino Unido", "Ucrânia"],
  OIC: ["Alemanha", "Arábia Saudita", "China", "Egito", "EUA", "França", "Iémen", "Iraque", "Irã", "Israel", "Líbano", "Paquistão", "Rússia"],
  FAO: ["Alemanha", "Argentina", "Brasil", "China", "Costa Rica", "Egito", "EUA", "França", "Haiti", "Índia", "Reino Unido", "Rússia", "Ucrânia"],
  ACNUDH: ["Alemanha", "África do Sul", "Bangladesh", "Brasil", "Chile", "China", "Coreia do Norte", "Costa Rica", "Cuba", "França", "Indonésia", "Japão", "Países Baixos"],
  UNICEF: ["Alemanha", "Brasil", "China", "EUA", "Equador", "Espanha", "França", "Índia", "Irlanda", "Nigéria", "Noruega", "Reino Unido", "Suíça"],
  OMS: ["África do Sul", "Alemanha", "Argentina", "Brasil", "Canadá", "China", "Cuba", "França", "Itália", "Japão", "Reino Unido", "Rússia", "Suíça"],
  UNODA: ["Alemanha", "Brasil", "China", "Coreia do Norte", "EUA", "França", "Irã", "Israel", "Japão", "Reino Unido", "República Democrática do Congo", "Rússia", "Ucrânia"],
  PNUD: ["Alemanha", "Brasil", "China", "Colômbia", "Coreia do Sul", "Dinamarca", "Equador", "EUA", "Etiópia", "Japão", "Luxemburgo", "Reino Unido", "Suécia"],
  AIEA: ["Austrália", "Brasil", "China", "Coreia do Norte", "Coreia do Sul", "EUA", "França", "Índia", "Irã", "Japão", "Reino Unido", "Rússia", "Ucrânia"],
  UNIDO: ["Alemanha", "Brasil", "Chile", "China", "Coreia do Sul", "EUA", "Países Baixos", "Índia", "Japão", "Nigéria", "República Democrática do Congo", "Taiwan", "Vietnã"],
  WMO: ["Arábia Saudita", "Austrália", "Brasil", "Canadá", "China", "Emirados Árabes Unidos", "EUA", "Índia", "Indonésia", "Quênia", "Rússia", "Suécia", "Tuvalu"],
  UNESCO: ["África do Sul", "China", "Egito", "EUA", "Finlândia", "França", "Índia", "Israel", "Itália", "Japão", "México", "Peru", "Ucrânia"],
  CSNU: ["África do Sul", "Brasil", "China", "EUA", "França", "Haiti", "Índia", "Israel", "Japão", "Reino Unido", "Rússia", "Sudão", "Ucrânia"],
  ACNUR: ["Afeganistão", "Alemanha", "Bangladesh", "Colômbia", "EUA", "Itália", "México", "Polônia", "Quênia", "Sudão", "Turquia", "Uganda", "Venezuela"],
  CCP: ["Brasil", "China", "Colômbia", "El Salvador", "Emirados Árabes Unidos", "Equador", "EUA", "Filipinas", "Itália", "México", "Nigéria", "Países Baixos", "Tailândia"],
  PNUMA: ["África do Sul", "Alemanha", "Brasil", "Canadá", "China", "EUA", "Indonésia", "Índia", "Japão", "Maldivas", "Nigéria", "Noruega"]
};
const classOptions = {
  "Manhã": { ADM: ["1º", "2º", "3º"], "D.S.": ["1º", "2º", "3º"], Eletrônica: ["1º", "2º", "3º"], Mecânica: ["1º", "2º", "3º"], Nutrição: ["1º", "2º", "3º"] },
  "Tarde": { ADM: ["1º", "2º", "3º"], "S. Jurídicos": ["1º"], "Mecatrônica": ["1º", "2º", "3º"], Gastronomia: ["1º"] }
};
const flagCodes = { "Afeganistão":"af","África do Sul":"za","Alemanha":"de","Arábia Saudita":"sa","Argentina":"ar","Austrália":"au","Bangladesh":"bd","Brasil":"br","Canadá":"ca","Chile":"cl","China":"cn","Colômbia":"co","Coreia do Norte":"kp","Coreia do Sul":"kr","Costa Rica":"cr","Cuba":"cu","Dinamarca":"dk","EUA":"us","Egito":"eg","El Salvador":"sv","Emirados Árabes Unidos":"ae","Equador":"ec","Espanha":"es","Etiópia":"et","Filipinas":"ph","Finlândia":"fi","França":"fr","Haiti":"ht","Iémen":"ye","Indonésia":"id","Índia":"in","Irã":"ir","Iraque":"iq","Irlanda":"ie","Israel":"il","Itália":"it","Japão":"jp","Líbano":"lb","Luxemburgo":"lu","Maldivas":"mv","México":"mx","Nigéria":"ng","Noruega":"no","Países Baixos":"nl","Paquistão":"pk","Peru":"pe","Polônia":"pl","Quênia":"ke","Reino Unido":"gb","República Democrática do Congo":"cd","Rússia":"ru","Sudão":"sd","Suécia":"se","Suíça":"ch","Taiwan":"tw","Tailândia":"th","Tuvalu":"tv","Turquia":"tr","Ucrânia":"ua","Uganda":"ug","Venezuela":"ve","Vietnã":"vn" };
const supabaseClient = window.supabase.createClient(window.ONUTEC_SUPABASE_URL, window.ONUTEC_SUPABASE_PUBLISHABLE_KEY);
const storageKey = "onutec-visitor-token";
const visitorToken = localStorage.getItem(storageKey) || crypto.randomUUID();
localStorage.setItem(storageKey, visitorToken);
const state = { mode: new URLSearchParams(window.location.search).get("consulta") === "1" ? "catalog" : "registration", step: 1, period: "", committee: "", country: "", slotId: "", personOne: "", yearOne: "", courseOne: "", classOne: "", personTwo: "", yearTwo: "", courseTwo: "", classTwo: "", loading: false, slots: [], catalogPeriod: "", catalogCommittee: "", catalogSlots: [], catalogLoading: false, registrationStatus: null };
const stage = document.querySelector("#stage");
const progress = document.querySelector("#progress-bar");
const stepLabel = document.querySelector("#step-label");
const statusLine = document.querySelector(".status-line");
const dialog = document.querySelector("#help-dialog");
let countdownTimer;
const escapeHtml = value => String(value || "").replace(/[&<>\"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const flag = country => `<img class="flag" src="https://flagcdn.com/w80/${flagCodes[country] || "un"}.png" srcset="https://flagcdn.com/w160/${flagCodes[country] || "un"}.png 2x" alt="" />`;

function render() { clearInterval(countdownTimer); if (state.mode === "catalog") { statusLine.hidden = true; stage.innerHTML = catalogView(); return; } const waiting = state.step === 1 && state.registrationStatus && !state.registrationStatus.is_open; statusLine.hidden = Boolean(waiting); stepLabel.textContent = state.step === 6 ? "Inscrição concluída" : `Passo ${state.step} de 5`; progress.style.width = `${Math.min(state.step, 5) * 20}%`; const views = { 1: periodView, 2: detailsView, 3: committeeView, 4: countryView, 5: confirmationView, 6: successView }; stage.innerHTML = views[state.step](); if (waiting) startCountdown(); }
function deviceClockReachedOpening() { return state.registrationStatus && !state.registrationStatus.is_open && Date.now() >= new Date(state.registrationStatus.opens_at).getTime(); }
function periodView() { if (state.registrationStatus && !state.registrationStatus.is_open && !deviceClockReachedOpening()) return countdownView(); return `<div class="choice-stack"><button class="choice" data-period="Manhã" type="button"><span class="choice-title">Manhã</span><span class="choice-arrow">→</span></button><button class="choice" data-period="Tarde" type="button"><span class="choice-title">Tarde</span><span class="choice-arrow">→</span></button></div>`; }
function countdownView() { const opensAt = new Date(state.registrationStatus.opens_at), date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "full", timeStyle: "short" }).format(opensAt); return `<section class="countdown-view"><h1>As inscrições<br><em>começam em</em></h1><div class="countdown" role="timer" aria-label="Contagem regressiva para a abertura das inscrições"><div><strong data-count="days">00</strong><span>dias</span></div><div><strong data-count="hours">00</strong><span>horas</span></div><div><strong data-count="minutes">00</strong><span>minutos</span></div><div><strong data-count="seconds">00</strong><span>segundos</span></div></div><p class="lead">Prepare sua dupla e escolha o comitê. A abertura está marcada para <strong>${date}</strong>.</p><div class="countdown-note"><i></i><p>Quando o relógio zerar, a tela será liberada. Se não abrir automaticamente, aperte <strong>F5</strong>.</p></div><div class="countdown-actions"><button class="catalog-cta" type="button" data-action="open-catalog"><span>Explorar comitês e países</span><b>→</b></button><button class="refresh-status" type="button" data-action="refresh-status">Atualizar agora</button></div></section>`; }
function catalogView() { if (!state.catalogPeriod) return `<section class="catalog-view"><p class="eyebrow">CONSULTA PÚBLICA</p><h1>Conheça as<br><em>delegações.</em></h1><p class="lead">Escolha o período para consultar comitês e países, sem iniciar uma inscrição.</p><div class="choice-stack"><button class="choice" data-catalog-period="Manhã" type="button"><span class="choice-title">Manhã</span><span class="choice-arrow">→</span></button><button class="choice" data-catalog-period="Tarde" type="button"><span class="choice-title">Tarde</span><span class="choice-arrow">→</span></button></div><button class="delegation-link" type="button" data-action="close-catalog">Voltar para inscrições</button></section>`; const back = `<button class="catalog-back" type="button" data-action="catalog-back">← Voltar</button>`; if (!state.catalogCommittee) return `<section class="catalog-view">${back}<p class="eyebrow">${escapeHtml(state.catalogPeriod.toUpperCase())}</p><h1>Comitês e<br><em>delegações.</em></h1><p class="lead">Toque em um comitê para ver os países disponíveis.</p><div class="catalog-committee-list">${Object.entries(committees).map(([name,countries])=>`<button class="catalog-committee" type="button" data-catalog-committee="${escapeHtml(name)}"><strong>${escapeHtml(name)}</strong><span>${countries.length} países <b>→</b></span></button>`).join("")}</div></section>`; if (state.catalogLoading) return `<section class="catalog-view">${back}<p class="eyebrow">${escapeHtml(state.catalogPeriod.toUpperCase())}</p><h1 class="committee-title">${escapeHtml(state.catalogCommittee)}</h1><p class="lead">Atualizando disponibilidade...</p></section>`; const countries=state.catalogSlots.map(slot=>`<div class="country catalog-country ${slot.availability === "available" ? "available" : "unavailable"}"><span>${flag(slot.country)}${escapeHtml(slot.country)}</span><small>${slot.availability === "available" ? "Disponível" : "Ocupado"}</small></div>`).join(""); return `<section class="catalog-view">${back}<p class="eyebrow">${escapeHtml(state.catalogPeriod.toUpperCase())} · CONSULTA</p><h1 class="committee-title">${escapeHtml(state.catalogCommittee)}</h1><p class="catalog-summary">${state.catalogSlots.filter(slot=>slot.availability === "available").length} de ${state.catalogSlots.length} países disponíveis</p><div class="country-list compact-list">${countries}</div></section>`; }
function startCountdown() { const target = new Date(state.registrationStatus.opens_at).getTime(); const update = async () => { const remaining = Math.max(0, target - Date.now()), totalSeconds = Math.floor(remaining / 1000), values = { days: Math.floor(totalSeconds / 86400), hours: Math.floor(totalSeconds % 86400 / 3600), minutes: Math.floor(totalSeconds % 3600 / 60), seconds: totalSeconds % 60 }; Object.entries(values).forEach(([unit, value]) => { const element = document.querySelector(`[data-count="${unit}"]`); if (element) element.textContent = String(value).padStart(2, "0"); }); if (!remaining) { clearInterval(countdownTimer); await loadRegistrationStatus(); } }; update(); countdownTimer = setInterval(update, 1000); }
function detailsView() { return `${periodBadge()}<p class="eyebrow">DADOS DA DUPLA</p><form id="details-form" novalidate><div class="form-grid">${field("personOne", "Nome do 1º integrante", "Nome completo", state.personOne)}${classField("one", "Turma do 1º integrante", state.yearOne, state.courseOne)}${field("personTwo", "Nome do 2º integrante", "Nome completo", state.personTwo)}${classField("two", "Turma do 2º integrante", state.yearTwo, state.courseTwo)}</div><p id="form-error" class="error" role="alert"></p><div class="actions"><button class="button secondary" type="button" data-action="back">Voltar</button><button class="button primary" type="submit">Escolher comitê</button></div></form>`; }
function field(name, label, placeholder, value) { return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" value="${escapeHtml(value)}" placeholder="${placeholder}" autocomplete="name" required /></div>`; }
function classField(member, label, year, course) { const courses=classOptions[state.period]||{}, years=courses[course]||[], suffix=member === "one" ? "One" : "Two"; return `<fieldset class="field class-field"><legend>${label}</legend><div class="class-selects"><select id="course-${member}" name="course${suffix}" aria-label="Curso do ${member === "one" ? "1º" : "2º"} integrante" required><option value="">Curso</option>${Object.keys(courses).map(item => `<option value="${item}" ${course === item ? "selected" : ""}>${item}</option>`).join("")}</select><select id="year-${member}" name="year${suffix}" aria-label="Ano do ${member === "one" ? "1º" : "2º"} integrante" required ${course?"":"disabled"}><option value="">Ano</option>${years.map(item => `<option value="${item}" ${year === item ? "selected" : ""}>${item}</option>`).join("")}</select></div></fieldset>`; }
function updateYearsForCourse(member, course) { const select=document.querySelector(`#year-${member}`), years=(classOptions[state.period]||{})[course]||[]; if (!select) return; select.disabled=!course; select.innerHTML=`<option value="">Ano</option>${years.map(year=>`<option value="${year}">${year}</option>`).join("")}`; }
function periodBadge() { return `<div class="period-badge" aria-label="Período escolhido">Período escolhido <strong>${state.period}</strong></div>`; }
function committeeView() { const options = Object.keys(committees).map((name, index) => `<button class="committee-chip" type="button" data-committee="${name}">${index + 1}. ${name}</button>`).join(""); return `${periodBadge()}<p class="eyebrow">ESCOLHA DO COMITÊ</p><div class="committee-select compact" role="group" aria-label="Escolha um comitê">${options}</div><div class="actions"><button class="button secondary" type="button" data-action="back">Voltar</button></div>`; }
function countryView() { if (state.loading) return `${periodBadge()}<h1 class="committee-title">${state.committee}</h1><p class="lead">Atualizando países disponíveis...</p>`; const countries = state.slots.map(slot => `<button class="country ${slot.availability === "available" ? "available" : "unavailable"}" type="button" ${slot.availability === "available" ? "" : "disabled"} data-slot-id="${slot.id}" data-country="${slot.country}"><span>${flag(slot.country)}${slot.country}</span><small>${slot.availability === "available" ? "Reservar" : "Indisponível"}</small></button>`).join(""); return `${periodBadge()}<h1 class="committee-title">${state.committee}</h1><p id="country-error" class="error" role="alert"></p><div class="country-list compact-list">${countries}</div><div class="actions"><button class="button secondary" type="button" data-action="back">Voltar</button></div>`; }
function confirmationView() { return `${periodBadge()}<p class="eyebrow">CONFIRA SEUS DADOS</p><h1>Revise antes de confirmar.</h1><div class="confirmation"><h2><img class="flag flag-large" src="https://flagcdn.com/w80/${flagCodes[state.country] || "un"}.png" srcset="https://flagcdn.com/w160/${flagCodes[state.country] || "un"}.png 2x" alt="" />${state.country}</h2><p class="lead">${state.committee} · ${state.period}</p><div class="confirmation-grid"><div><small>Integrante 1</small><strong>${escapeHtml(state.personOne)}</strong><span>${escapeHtml(state.classOne)}</span></div><div><small>Integrante 2</small><strong>${escapeHtml(state.personTwo)}</strong><span>${escapeHtml(state.classTwo)}</span></div></div></div><div class="reserve-strip"><strong>Importante:</strong> após confirmar, apenas a organização poderá alterar a inscrição.</div><div class="actions"><button class="button secondary" type="button" data-action="release">Trocar país</button><button class="button primary" type="button" data-action="confirm">Confirmar inscrição</button></div>`; }
function successView() { return `${periodBadge()}<div class="success-mark">✓</div><p class="eyebrow">INSCRIÇÃO CONFIRMADA</p><h1>Até a próxima sessão.</h1><p class="lead">Sua dupla foi inscrita para representar <strong>${state.country}</strong> no comitê ${state.committee}, período da ${state.period.toLowerCase()}.</p><div class="confirmation"><h2><img class="flag flag-large" src="https://flagcdn.com/w80/${flagCodes[state.country] || "un"}.png" srcset="https://flagcdn.com/w160/${flagCodes[state.country] || "un"}.png 2x" alt="" />${state.country} · ${state.committee}</h2><p class="lead">${escapeHtml(state.personOne)} e ${escapeHtml(state.personTwo)}</p><p class="confirmation-classes"><strong>Turmas:</strong> ${escapeHtml(state.classOne)} · ${escapeHtml(state.classTwo)}</p></div><p class="note"><strong>✓</strong><span>Guarde esta confirmação. Caso precise corrigir algo, procure a organização do evento.</span></p>`; }
async function loadSlots() { state.loading = true; render(); const { data, error } = await supabaseClient.rpc("list_event_slots", { p_period: state.period, p_committee: state.committee }); state.loading = false; state.slots = data || []; render(); if (error) showCountryError("Não foi possível carregar os países. Tente novamente."); }
async function loadCatalogSlots() { state.catalogLoading = true; render(); const { data } = await supabaseClient.rpc("list_event_slots", { p_period: state.catalogPeriod, p_committee: state.catalogCommittee }); state.catalogSlots = data || []; state.catalogLoading = false; render(); }
function showCountryError(message) { const error = document.querySelector("#country-error"); if (error) error.textContent = message; }
async function reserveCountry(slotId, country) { const { data, error } = await supabaseClient.rpc("reserve_event_slot", { p_slot_id: slotId, p_visitor_token: visitorToken }); const result = data && data[0] && data[0].result; if (error || result !== "reserved") { await loadSlots(); showCountryError(result === "already_reserved" ? "Você já possui uma escolha em andamento. Volte para ela ou aguarde alguns minutos." : result === "closed" ? "Você tentou antecipar a abertura. A tentativa foi registrada para a organização." : "Este país acabou de ser escolhido por outra dupla. Selecione outro."); return; } state.loading = false; state.slotId = slotId; state.country = country; state.step = 5; render(); }
async function releaseCountry() { if (state.slotId) await supabaseClient.rpc("release_event_slot", { p_slot_id: state.slotId, p_visitor_token: visitorToken }); state.slotId = ""; state.country = ""; state.step = 4; await loadSlots(); }
async function confirmRegistration() { const button = document.querySelector('[data-action="confirm"]'); if (button) { button.disabled = true; button.textContent = "Confirmando..."; } const { error } = await supabaseClient.rpc("confirm_event_registration", { p_slot_id: state.slotId, p_visitor_token: visitorToken, p_member_one_name: state.personOne, p_member_one_class: state.classOne, p_member_two_name: state.personTwo, p_member_two_class: state.classTwo }); if (error) { if (button) { button.disabled = false; button.textContent = "Confirmar inscrição"; } alert("Não foi possível concluir esta inscrição. O país pode não estar mais disponível. Escolha outro e tente novamente."); await releaseCountry(); return; } state.step = 6; render(); }
document.addEventListener("click", async event => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.action === "open-catalog") { state.mode = "catalog"; state.catalogPeriod = ""; state.catalogCommittee = ""; render(); } else if (button.dataset.action === "close-catalog") { state.mode = "registration"; render(); } else if (button.dataset.action === "catalog-back") { if (state.catalogCommittee) { state.catalogCommittee = ""; state.catalogSlots = []; } else state.catalogPeriod = ""; render(); } else if (button.dataset.catalogPeriod) { state.catalogPeriod = button.dataset.catalogPeriod; render(); } else if (button.dataset.catalogCommittee) { state.catalogCommittee = button.dataset.catalogCommittee; await loadCatalogSlots(); } else if (button.dataset.period) { state.period = button.dataset.period; state.step = 2; render(); } else if (button.dataset.committee) { state.committee = button.dataset.committee; state.step = 4; await loadSlots(); } else if (button.dataset.slotId) { state.loading = true; render(); await reserveCountry(button.dataset.slotId, button.dataset.country); } else if (button.dataset.action === "back") { state.step = Math.max(1, state.step - 1); render(); } else if (button.dataset.action === "release") { await releaseCountry(); } else if (button.dataset.action === "confirm") { await confirmRegistration(); } else if (button.dataset.action === "refresh-status") { button.disabled = true; button.textContent = "Atualizando..."; await loadRegistrationStatus(); } else if (button.dataset.action === "help") { dialog.showModal(); } else if (button.dataset.action === "close-help") { dialog.close(); } });
document.addEventListener("submit", event => { if (event.target.id !== "details-form") return; event.preventDefault(); const data = new FormData(event.target); ["personOne", "yearOne", "courseOne", "personTwo", "yearTwo", "courseTwo"].forEach(key => state[key] = String(data.get(key) || "").trim()); state.classOne = `${state.yearOne} ${state.courseOne}`.trim(); state.classTwo = `${state.yearTwo} ${state.courseTwo}`.trim(); const error = document.querySelector("#form-error"); if (!state.personOne || !state.yearOne || !state.courseOne || !state.personTwo || !state.yearTwo || !state.courseTwo) { error.textContent = "Preencha os dados dos dois integrantes para continuar."; return; } state.step = 3; render(); });
document.addEventListener("change", event => { if (!event.target.matches("[id^=course-]")) return; updateYearsForCourse(event.target.id.replace("course-", ""), event.target.value); });
async function loadRegistrationStatus() { const { data } = await supabaseClient.rpc("get_registration_status"); state.registrationStatus = data && data[0] ? data[0] : null; render(); }
loadRegistrationStatus();
