const committeesByPeriod = {
  "Manhã": {
    "ONU Mulheres": ["Afeganistão", "África do Sul", "Alemanha", "Arábia Saudita", "Canadá", "China", "EUA", "Índia", "Japão", "Noruega", "Países Baixos", "Reino Unido", "Ucrânia"],
    OIC: ["Alemanha", "Arábia Saudita", "China", "Egito", "EUA", "França", "Iémen", "Irã", "Iraque", "Israel", "Líbano", "Paquistão", "Rússia"],
    FAO: ["Alemanha", "Argentina", "Brasil", "China", "Costa Rica", "Egito", "EUA", "França", "Haiti", "Índia", "Reino Unido", "Rússia", "Ucrânia"],
    ACNUDH: ["Alemanha", "África do Sul", "Bangladesh", "Brasil", "Chile", "China", "Coreia do Norte", "Costa Rica", "Cuba", "França", "Indonésia", "Japão", "Países Baixos"],
    UNICEF: ["Alemanha", "Brasil", "China", "EUA", "Equador", "Espanha", "França", "Índia", "Irlanda", "Nigéria", "Noruega", "Reino Unido", "Suíça"],
    OMS: ["África do Sul", "Alemanha", "Argentina", "Brasil", "Canadá", "China", "Cuba", "França", "Itália", "Japão", "Reino Unido", "Rússia", "Suíça"],
    UNODA: ["Alemanha", "Brasil", "China", "Coreia do Norte", "EUA", "França", "Irã", "Israel", "Japão", "Reino Unido", "República Democrática do Congo", "Rússia", "Ucrânia"],
    PNUD: ["Alemanha", "Brasil", "China", "Colômbia", "Coreia do Sul", "Dinamarca", "Equador", "EUA", "Etiópia", "Japão", "Luxemburgo", "Reino Unido", "Suécia"],
    AIEA: ["Austrália", "Brasil", "China", "Coreia do Norte", "Coreia do Sul", "EUA", "França", "Índia", "Irã", "Japão", "Reino Unido", "Rússia", "Ucrânia"],
    UNIDO: ["Alemanha", "Brasil", "Chile", "China", "Coreia do Sul", "EUA", "Países Baixos", "Índia", "Japão", "Nigéria", "República Democrática do Congo", "Taiwan", "Vietnã"],
    WMO: ["Arábia Saudita", "Austrália", "Brasil", "Canadá", "China", "Emirados Árabes Unidos", "EUA", "Índia", "Indonésia", "Quênia", "Rússia", "Suécia", "Tuvalu"],
    UNESCO: ["África do Sul", "China", "Egito", "EUA", "Finlândia", "França", "Índia", "Israel", "Itália", "Japão", "México", "Peru", "Ucrânia"],
    CSNU: ["África do Sul", "Brasil", "China", "EUA", "França", "Haiti", "Índia", "Israel", "Japão", "Reino Unido", "Rússia", "Sudão", "Ucrânia"],
    ACNUR: ["Afeganistão", "Alemanha", "Bangladesh", "Colômbia", "EUA", "Itália", "México", "Polônia", "Quênia", "Sudão", "Turquia", "Uganda", "Venezuela"],
    CCP: ["Brasil", "China", "Colômbia", "El Salvador", "Emirados Árabes Unidos", "Equador", "EUA", "Filipinas", "Itália", "México", "Nigéria", "Países Baixos", "Tailândia"],
    PNUMA: ["África do Sul", "Alemanha", "Brasil", "Canadá", "China", "EUA", "Indonésia", "Índia", "Japão", "Maldivas", "Nigéria", "Noruega"]
  },
  "Tarde": {
    "ONU Mulheres": ["Afeganistão", "África do Sul", "Alemanha", "Arábia Saudita", "Canadá", "China", "EUA", "Índia", "Japão", "Noruega", "Países Baixos", "Reino Unido", "Ucrânia"],
    ACNUDH: ["Alemanha", "África do Sul", "Bangladesh", "Brasil", "Chile", "China", "Coreia do Norte", "Costa Rica", "Cuba", "França", "Indonésia", "Japão", "Países Baixos"],
    OMS: ["África do Sul", "Alemanha", "Argentina", "Brasil", "Canadá", "China", "Cuba", "França", "Itália", "Japão", "Reino Unido", "Rússia", "Suíça"],
    UNODA: ["Alemanha", "Brasil", "China", "Coreia do Norte", "EUA", "França", "Irã", "Israel", "Japão", "Reino Unido", "República Democrática do Congo", "Rússia", "Ucrânia"],
    CSNU: ["África do Sul", "Brasil", "China", "EUA", "França", "Haiti", "Índia", "Israel", "Japão", "Reino Unido", "Rússia", "Sudão", "Ucrânia"],
    ACNUR: ["Afeganistão", "Alemanha", "Bangladesh", "Colômbia", "EUA", "Itália", "México", "Polônia", "Quênia", "Sudão", "Turquia", "Uganda", "Venezuela"],
    CCP: ["Brasil", "China", "Colômbia", "El Salvador", "Emirados Árabes Unidos", "Equador", "EUA", "Filipinas", "Itália", "México", "Nigéria", "Países Baixos", "Tailândia"],
    FAO: ["Alemanha", "Argentina", "Brasil", "China", "Costa Rica", "Egito", "EUA", "França", "Haiti", "Índia", "Reino Unido", "Rússia", "Ucrânia"],
    UNICEF: ["Alemanha", "Brasil", "China", "EUA", "Equador", "Espanha", "França", "Índia", "Irlanda", "Nigéria", "Noruega", "Reino Unido", "Suíça"],
    UNESCO: ["África do Sul", "China", "Egito", "EUA", "Finlândia", "França", "Índia", "Israel", "Itália", "Japão", "México", "Peru", "Ucrânia"]
  }
};

// Snapshot público capturado em 26/09/2026. A posição acompanha a lista acima.
const availabilitySnapshot = {
  "Manhã": { "ONU Mulheres": ["available","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied"], OIC: ["occupied","occupied","occupied","occupied","occupied","occupied","occupied","available","occupied","available","occupied","occupied","occupied"], FAO: Array(13).fill("occupied"), ACNUDH: Array(13).fill("occupied"), UNICEF: Array(13).fill("occupied"), OMS: Array(13).fill("occupied"), UNODA: ["occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied","available"], PNUD: Array(13).fill("occupied"), AIEA: Array(13).fill("occupied"), UNIDO: Array(13).fill("occupied"), WMO: Array(13).fill("occupied"), UNESCO: Array(13).fill("occupied"), CSNU: Array(13).fill("occupied"), ACNUR: Array(13).fill("occupied"), CCP: ["occupied","occupied","occupied","occupied","available","occupied","occupied","occupied","occupied","occupied","occupied","occupied","occupied"], PNUMA: Array(12).fill("occupied") },
  "Tarde": { "ONU Mulheres": Array(13).fill("occupied"), ACNUDH: ["available","occupied","available","occupied","available","occupied","occupied","available","available","occupied","available","occupied","occupied"], OMS: ["occupied","occupied","occupied","occupied","occupied","available","occupied","occupied","occupied","occupied","available","occupied","occupied"], UNODA: ["occupied","available","occupied","available","occupied","occupied","available","available","occupied","available","available","occupied","available"], CSNU: ["available","occupied","available","occupied","occupied","occupied","available","occupied","available","occupied","available","available","available"], ACNUR: ["available","occupied","available","occupied","available","occupied","occupied","available","available","available","occupied","available","available"], CCP: ["occupied","available","available","available","available","available","available","available","occupied","available","available","occupied","available"], FAO: Array(13).fill("occupied"), UNICEF: Array(13).fill("occupied"), UNESCO: ["occupied","occupied","available","occupied","occupied","occupied","available","available","occupied","occupied","occupied","occupied","available"] }
};

const flagCodes = { "Afeganistão":"af", "África do Sul":"za", "Alemanha":"de", "Arábia Saudita":"sa", "Argentina":"ar", "Austrália":"au", "Bangladesh":"bd", "Brasil":"br", "Canadá":"ca", "Chile":"cl", "China":"cn", "Colômbia":"co", "Coreia do Norte":"kp", "Coreia do Sul":"kr", "Costa Rica":"cr", "Cuba":"cu", "Dinamarca":"dk", "EUA":"us", "Egito":"eg", "El Salvador":"sv", "Emirados Árabes Unidos":"ae", "Equador":"ec", "Espanha":"es", "Etiópia":"et", "Filipinas":"ph", "Finlândia":"fi", "França":"fr", "Haiti":"ht", "Iémen":"ye", "Indonésia":"id", "Índia":"in", "Irã":"ir", "Iraque":"iq", "Irlanda":"ie", "Israel":"il", "Itália":"it", "Japão":"jp", "Líbano":"lb", "Luxemburgo":"lu", "Maldivas":"mv", "México":"mx", "Nigéria":"ng", "Noruega":"no", "Países Baixos":"nl", "Paquistão":"pk", "Peru":"pe", "Polônia":"pl", "Quênia":"ke", "Reino Unido":"gb", "República Democrática do Congo":"cd", "Rússia":"ru", "Sudão":"sd", "Suécia":"se", "Suíça":"ch", "Taiwan":"tw", "Tailândia":"th", "Tuvalu":"tv", "Turquia":"tr", "Ucrânia":"ua", "Uganda":"ug", "Venezuela":"ve", "Vietnã":"vn" };

const escapeHtml = value => String(value ?? "").replace(/[&<>\"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const normalizeSearch = value => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\p{L}\p{N}]+/gu, " ").trim().toLocaleLowerCase("pt-BR");
const catalogRoute = window.location.pathname.replace(/\/$/, "") === "/comites";
const legacyCatalogRoute = new URLSearchParams(window.location.search).has("consulta");
if (!catalogRoute && legacyCatalogRoute) history.replaceState({}, "", "/comites");
const state = { period: "", committee: "", room: "", view: "committees", searchTerm: "", searchMode: "all" };
const stage = document.querySelector("#stage");
const helpDialog = document.querySelector("#help-dialog");

function snapshotFor(period, committee) { const countries = committeesByPeriod[period]?.[committee] || []; const statuses = availabilitySnapshot[period]?.[committee] || []; return countries.map((country, index) => { const registration = (window.ONUTEC_REGISTRATIONS || []).find(item => item.period === period && item.committee === committee && item.country === country); return { country, availability: registration ? "occupied" : (statuses[index] || "occupied"), registration }; }); }
function flag(country) { const code = flagCodes[country] || "un"; return `<img class="flag" src="https://flagcdn.com/w40/${code}.png" srcset="https://flagcdn.com/w80/${code}.png 2x" alt="Bandeira de ${escapeHtml(country)}" loading="lazy" /><span>${escapeHtml(country)}</span>`; }
function searchResults() { const term = normalizeSearch(state.searchTerm); if (!term) return ""; const fields = state.searchMode === "committee" ? ["committee"] : state.searchMode === "student-room" ? ["turma", "turma_1", "turma_2", "sala_aluno", "member_one_class", "member_two_class", "class_one", "class_two"] : ["period", "committee", "country", "integrante_1", "integrante_2", "sala", "turma", "turma_1", "turma_2"]; const results = (window.ONUTEC_REGISTRATIONS || []).filter(item => fields.some(field => normalizeSearch(item[field]).includes(term))).slice(0, 60); const emptyMessage = state.searchMode === "student-room" ? "Nenhuma turma encontrada. Tente buscar pelo nome da turma." : "Nenhum resultado encontrado"; return `<div class="search-results"><p class="search-count">${results.length ? `${results.length}${results.length === 60 ? "+" : ""} resultado${results.length === 1 ? "" : "s"}` : emptyMessage}</p>${results.map(item => `<article class="search-result"><div><strong>${escapeHtml(item.integrante_1)} e ${escapeHtml(item.integrante_2)}</strong><span>${escapeHtml(item.period)} · ${escapeHtml(item.committee)} · ${escapeHtml(item.country)} · ${escapeHtml(item.turma_1 || "")} / ${escapeHtml(item.turma_2 || "")}</span></div></article>`).join("")}</div>`; }
function classesFor(period) { return [...new Set((window.ONUTEC_REGISTRATIONS || []).filter(item => item.period === period).flatMap(item => [item.turma_1, item.turma_2]).filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR", { numeric: true })); }
function classRegistrations(period, className) { return (window.ONUTEC_REGISTRATIONS || []).filter(item => item.period === period && [item.turma_1, item.turma_2].includes(className)); }
function studentsForClass(registrations, className) { return registrations.flatMap(item => [item.turma_1 === className ? { name: item.integrante_1, partner: item.integrante_2, committee: item.committee, country: item.country } : null, item.turma_2 === className ? { name: item.integrante_2, partner: item.integrante_1, committee: item.committee, country: item.country } : null]).filter(Boolean).sort((a, b) => a.name.localeCompare(b.name, "pt-BR")); }
function studentRows(students) { return students.map(student => `<article class="search-result"><div><strong>${escapeHtml(student.name)}</strong><span>Dupla: ${escapeHtml(student.partner)} · ${escapeHtml(student.committee)} · ${escapeHtml(student.country)}</span></div></article>`).join(""); }
function render() {
  if (!state.period) { const searchLabel = state.searchMode === "committee" ? "Pesquisar por comitê" : state.searchMode === "student-room" ? "Pesquisar turma do aluno" : "Pesquisar inscrições"; const placeholder = state.searchMode === "committee" ? "Ex.: CSNU ou ACNUDH" : state.searchMode === "student-room" ? "Ex.: 1º ADM ou 2º Eletrônica" : "Ex.: Ana, ACNUDH ou 1º Mecânica"; stage.innerHTML = `<section class="catalog-view"><p class="eyebrow">CONSULTA PÚBLICA</p><h1>Consulte as<br><em>delegações.</em></h1><p class="lead">Pesquise por nome, comitê, país ou turma, ou navegue pelo período.</p><label class="catalog-search"><span>${searchLabel}</span><input id="catalog-search" type="search" value="${escapeHtml(state.searchTerm)}" placeholder="${placeholder}" autocomplete="off" /></label>${searchResults()}<div class="choice-stack">${Object.keys(committeesByPeriod).map(period => `<button class="choice" type="button" data-period="${period}"><span class="choice-title">${period}</span><span class="choice-arrow">→</span></button>`).join("")}</div></section>`; return; }
  const back = `<button class="catalog-back" type="button" data-action="back">← Voltar</button>`;
  if (!state.committee && !state.room) { const tab = `<div class="catalog-tabs" role="tablist" aria-label="Tipo de consulta"><button class="browse-button ${state.view === "committees" ? "active" : ""}" type="button" data-view="committees">Comitês</button><button class="browse-button ${state.view === "rooms" ? "active" : ""}" type="button" data-view="rooms">Turmas</button></div>`; if (state.view === "rooms") { const classes = classesFor(state.period); stage.innerHTML = `<section class="catalog-view">${back}<p class="eyebrow">${state.period.toUpperCase()} · CONSULTA</p><h1>Turmas e<br><em>alunos.</em></h1><p class="lead">Selecione uma turma para consultar os alunos que pertencem a ela.</p>${tab}<div class="catalog-committee-list">${classes.length ? classes.map(className => { const count = classRegistrations(state.period, className).length; return `<button class="catalog-committee" type="button" data-room="${escapeHtml(className)}"><strong>${escapeHtml(className)}</strong><span>${count} ${count === 1 ? "dupla" : "duplas"} <b>→</b></span></button>`; }).join("") : `<p class="note"><strong>Nenhuma turma informada.</strong><span>As turmas ainda não estão preenchidas no snapshot.</span></p>`}</div></section>`; return; } stage.innerHTML = `<section class="catalog-view">${back}<p class="eyebrow">${state.period.toUpperCase()} · CONSULTA</p><h1>Comitês e<br><em>delegações.</em></h1><p class="lead">Selecione um comitê para consultar os países e o estado final de cada delegação.</p>${tab}<div class="catalog-committee-list">${Object.keys(committeesByPeriod[state.period]).map(committee => { const rows = snapshotFor(state.period, committee); const occupied = rows.filter(row => row.availability === "occupied").length; return `<button class="catalog-committee" type="button" data-committee="${escapeHtml(committee)}"><strong>${escapeHtml(committee)}</strong><span>${occupied} de ${rows.length} ocupados <b>→</b></span></button>`; }).join("")}</div></section>`; return; }
  if (state.room) { const registrations = classRegistrations(state.period, state.room); const students = studentsForClass(registrations, state.room); const studentCount = students.length; stage.innerHTML = `<section class="catalog-view">${back}<p class="eyebrow">${state.period.toUpperCase()} · TURMA</p><h1 class="committee-title">${escapeHtml(state.room)}</h1><p class="catalog-summary">${studentCount} ${studentCount === 1 ? "aluno encontrado" : "alunos encontrados"}</p><div class="search-results room-results">${studentRows(students)}</div><p class="note"><strong>Consulta encerrada:</strong><span>Este conteúdo é estático e não recebe novas inscrições ou alterações.</span></p></section>`; return; }
  const rows = snapshotFor(state.period, state.committee); const occupied = rows.filter(row => row.availability === "occupied").length;
  stage.innerHTML = `<section class="catalog-view">${back}<p class="eyebrow">${state.period.toUpperCase()} · CONSULTA</p><h1 class="committee-title">${escapeHtml(state.committee)}</h1><p class="catalog-summary">${occupied} de ${rows.length} delegações ocupadas no snapshot final</p><div class="country-list compact-list">${rows.map(row => { const registration = row.registration; return `<article class="delegation ${row.availability}"><div class="delegation-country"><span>${flag(row.country)}</span><small>${row.availability === "available" ? "Disponível" : "Ocupada"}</small></div>${registration ? `<div class="delegation-members"><div><small>Integrante 1</small><strong>${escapeHtml(registration.integrante_1)}</strong><span class="member-class">${escapeHtml(registration.turma_1 || "Turma não informada")}</span></div><div><small>Integrante 2</small><strong>${escapeHtml(registration.integrante_2)}</strong><span class="member-class">${escapeHtml(registration.turma_2 || "Turma não informada")}</span></div></div><div class="delegation-room"><small>Sala</small><strong>${escapeHtml(registration.sala || "Sala a definir")}</strong></div>` : ""}</article>`; }).join("")}</div><p class="note"><strong>Consulta encerrada:</strong><span>Este conteúdo é estático e não recebe novas inscrições ou alterações.</span></p></section>`;
}
document.addEventListener("input", event => { if (event.target.id !== "catalog-search") return; state.searchTerm = event.target.value; const cursor = event.target.selectionStart; render(); const input = document.querySelector("#catalog-search"); if (input) { input.focus(); input.setSelectionRange(cursor, cursor); } });
document.addEventListener("click", event => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.browse) { state.searchMode = button.dataset.browse; state.searchTerm = ""; state.period = ""; state.committee = ""; state.room = ""; render(); } else if (button.dataset.period) { state.period = button.dataset.period; state.committee = ""; state.room = ""; state.view = "committees"; render(); } else if (button.dataset.view) { state.view = button.dataset.view; state.committee = ""; state.room = ""; render(); } else if (button.dataset.committee) { state.committee = button.dataset.committee; state.room = ""; render(); } else if (button.dataset.room) { state.room = button.dataset.room; state.committee = ""; render(); } else if (button.dataset.action === "back") { if (state.committee || state.room) { state.committee = ""; state.room = ""; } else state.period = ""; render(); } else if (button.dataset.action === "help") helpDialog.showModal(); else if (button.dataset.action === "close-help") helpDialog.close(); });
render();
